spring:
  application:
    name: cine-crew

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  cache:
    type: redis
    cache-names:
      - club-rankings
    redis:
      time-to-live: 10m
      cache-null-values: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}

  ai:
    model:
      chat:
        openai:
          base-url: https://generativelanguage.googleapis.com/v1beta/openai
          api-key: ${GEMINI_API_KEY}
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.7


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  port: ${SERVER_PORT}

rsa:
  public-key: classpath:certs/public.key
  private-key: classpath:certs/private.key

app:
  frontend-url: ${FRONTEND_URL}
  invite:
    ttl-minutes: ${INVITE_TTL_MINUTES}
  security:
    jwt:
      expiration-minutes: ${JWT_EXPIRATION_MINUTES}
      issuer: ${JWT_ISSUER}

springdoc:
  api-docs:
    path: /openapi

  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true

logging:
  level:
    org.hibernate.SQL: WARN
    br.com.cinecrew: DEBUG

tmdb:
  base-url: https://api.themoviedb.org/3
  access-token: ${TMDB_ACCESS_TOKEN}
  image-base-url: https://image.tmdb.org/t/p/w500